#!/usr/bin/python3

import fileinput
import optparse
import os.path
import sys
import xml.sax.saxutils

import tenorsax.sources.troff.parse
import tenorsax.filters.xslt

dirs = {
    "tmac": ("/usr/local/share/tenorsax/tmac", "/usr/share/tenorsax/tmac",
        "/usr/local/share/tmac", "/usr/share/tmac",
        "/usr/share/groff/current/tmac", "./tmac"),
    "xslt": ("/usr/local/share/tenorsax/xslt", "/usr/share/tenorsax/xslt",
        "./xslt")
}

suffixes = {"tmac": (".tmac",), "xslt": (".xsl",)}

def find_first(type_, name):
    try:
        lst = dirs[type_]
    except KeyError:
        return None
    try:
        suff = list(suffixes[type_])
        suff.append("")
    except KeyError:
        return None
    for j in suff:
        for i in lst:
            possible = i + "/" + name + j
            if os.path.exists(possible):
                return possible
    return None

parser = optparse.OptionParser()
parser.add_option("-T", dest="fmt", default="troff-xml")
parser.add_option("-s", dest="stylesheet")
(options, args) = parser.parse_args()

writer = xml.sax.saxutils.XMLGenerator(encoding="UTF-8")
if options.stylesheet:
    f = tenorsax.filters.xslt.XSLTTransformer(writer, options.stylesheet)
elif options.fmt in ("xml", "fo"):
    ssheet = find_first("xslt", "format-" + options.fmt)
    f = tenorsax.filters.xslt.XSLTTransformer(writer, ssheet)
elif options.fmt == "test":
    f = tenorsax.filters.xslt.TextXSLTTransformer(sys.stdout, "xslt/trim.xsl")
else:
    f = writer
p = tenorsax.sources.troff.parse.Parser(f)
p.parse(fileinput.input(files=args))
